# Generated by Django 5.2.11 on 2026-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0026_sourcenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitizedwork",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
