# Generated by Django 5.2.11 on 2026-03-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0027_digitizedwork_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="adapter_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the adapter to use for works in this collection (optional)",
                max_length=100,
            ),
        ),
    ]
