# Generated by Django 5.2.11 on 2026-03-11 15:40

from django.db import migrations


def populate_adapter_names(apps, schema_editor):
    """Populate adapter_name based on works' source_id prefixes."""
    Collection = apps.get_model("archive", "Collection")

    for collection in Collection.objects.all():
        works = collection.digitizedwork_set.all()[:10]  # Sample first 10 works
        if not works:
            continue

        source_prefixes = [w.source_id.split("_")[0] for w in works if w.source_id]

        # If all have same prefix, set adapter
        if all(p == "scifi" for p in source_prefixes):
            collection.adapter_name = "scifi"
            collection.save()
        elif all(p in ["cookbook", "feeding"] for p in source_prefixes):
            collection.adapter_name = "cookbook"
            collection.save()


def reverse_populate(apps, schema_editor):
    """Clear adapter_name on rollback."""
    Collection = apps.get_model("archive", "Collection")
    Collection.objects.update(adapter_name="")


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0028_add_collection_adapter_name"),
    ]

    operations = [
        migrations.RunPython(populate_adapter_names, reverse_populate),
    ]
