# Generated by Django 5.2.11 on 2026-03-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0029_populate_collection_adapters"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="list_view_fields",
            field=models.JSONField(
                blank=True,
                help_text="Custom fields to display in list view (JSON array). Leave empty to use adapter defaults.",
                null=True,
            ),
        ),
    ]
